language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

# run builds for both all the trains
rust:
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "XpEJ9/OHrCfscVvQJn7s2DyWeRUZwDX2Vlfm9QVvzy8LmVFUi604pNuI6ipwcMEF2MTHmqOFGx/7DwgOhJ/xF+Ch8abxMkUxENlGIfzmbDz5i+8zVL1cbIiMaltHfji92vwxiss8Tlo+D1s+DrAZUfBbhDZ3dhPnLlVg+IxId3vxB3W/7QQqntJiKnfJywBaP/nMpvnkDqzy20xaUhLKzbmsH6co0h7UcpoywfP5X9+961sKfapta2r9VutsUKvSFkYS2mWT22xxXC6XC25lIiRN8Vzry57GbcwRkwU4CiWMV5UFZE0fCur80fYYkDBwI1mfvM+uQX9SWCFTv9TMu8h9ri9VoSdGSRtD+AvjaxPrwmGks/3LN2BsjfCFR5Mz+JnxX/xZOjTAMtzaACSNkjBMCrnvGNqpXdzzDuuFwvU+mCZeNGL024HgFIfFpxv0IdIibs/A+2kQHsjzebqFadSZqCp8HeqPbvNX98Rp2UeFZvBxsno24J1oNAYGeqgWsfverAPlfnmsJBRHfY4Z0A7Nu3GjVxqztoQAqyiIq01L0RCaMWnjxahAipNMBYdvJNnHT5sqcQ+7zM1INrFVR7NIrAMLfuZwjvfa/X9AEefDkDX+igo8vDvaBpPdz4IVU6tbOWoLZd8IpZLjJmo33QQxHcKV2/5KLvxBIBDBOoU="
